feat: publish to centrality external

diff --git a/ci/deployment/Dockerfile b/ci/deployment/Dockerfile
--- a/ci/deployment/Dockerfile
+++ b/ci/deployment/Dockerfile
@@ -5,7 +5,10 @@ WORKDIR workdir/
 ARG GIT_NAME
 ARG GIT_EMAIL
 ARG GEMFURY_TOKEN
+ARG GEMFURY_EXTERNAL_TOKEN
 ARG RELEASE_SCOPE
+
+ENV npm_config_registry="https://npm-proxy.fury.io/$GEMFURY_EXTERNAL_TOKEN/centralityexternals/"
 
 # add credentials on build
 RUN mkdir /root/.ssh/
@@ -52,6 +55,28 @@ RUN \
     -- \
       "\
         PUSH_URL=\"https://${GEMFURY_TOKEN}@push.fury.io/centrality/\" && \
+        PACKAGE_NAME=\$(node -p \"try {require('./package.json').name} catch(e){'0.0.0'}\") && \
+        PACKAGE_VERSION=\$(node -p \"try {require('./package.json').version} catch(e){'0.0.0'}\") && \
+        TAR_PATH=\"\$(pwd)/\${PACKAGE_NAME}-\${PACKAGE_VERSION}.tgz\" && \
+        if [ ! -f TAR_PATH ]; then continue; fi && \
+        echo \" - Pushing package: \$PACKAGE_NAME\" && \
+        ( \
+          RESPONSE=\$(curl -sS -F package=@\${TAR_PATH} \${PUSH_URL}) && \
+          echo \"\${RESPONSE}\" && \
+          case \"\${RESPONSE}\" in \
+            *\"... ok\"*) echo \" - Pushed package: \$PACKAGE_NAME\";; \
+            *        ) (echo \" - Failed to push package: \$PACKAGE_NAME\" && exit 1);; \
+          esac \
+        ); \
+      ";
+
+# push all packages to Gemfury centrality external
+RUN \
+  echo 'Pushing packages \${workdir} to Gemfury' && \
+  npx lerna exec --scope={cennznet-api,cennznet-types,cennznet-wallet,cennznet-runtime-types} \
+    -- \
+      "\
+        PUSH_URL=\"https://${GEMFURY_EXTERNAL_TOKEN}@push.fury.io/centralityexternals/\" && \
         PACKAGE_NAME=\$(node -p \"try {require('./package.json').name} catch(e){'0.0.0'}\") && \
         PACKAGE_VERSION=\$(node -p \"try {require('./package.json').version} catch(e){'0.0.0'}\") && \
         TAR_PATH=\"\$(pwd)/\${PACKAGE_NAME}-\${PACKAGE_VERSION}.tgz\" && \
